[mgr]
sort_by = "natural"
linemode = "size"
show_hidden = true

[opener]
play = [
	{run = 'vlc "$@"', orphan = true, for = "unix"}
]
edit = [
	{run = '$EDITOR "$@"', block = true, for = "unix"}
]
open = [
	{run = 'xdg-open "$@"', desc = "Open"}
]
