for_window [app_id="org.prismlauncher.PrismLauncher"] floating enable
for_window [app_id="thunar"] floating enable
for_window [class="Pcmanfm"] floating enable
for_window [app_id="com.github.hluk.copyq"] floating enable
for_window [app_id="com.mitchellh.ghostty"] opacity 0.9
for_window [app_id="org.pulseaudio.pavucontrol"] floating true
# for_window [class="Etterna"] floating enable
for_window [app_id="qalculate_gtk"] floating enable
for_window [class="zoom"] floating enable
for_window [class="Nsxiv"] floating enable

# Steam stuff
for_window [class="^steam$"] floating enable
for_window [class="^Steam$"] floating enable
for_window [class="^steam$" title="^Steam$"] floating disable
