set $mod Mod4

bindsym XF86MonBrightnessUp exec lightctl -d -e 2 up 
bindsym XF86MonBrightnessDown exec lightctl -d -e 2 down
bindsym Print exec --no-startup-id flameshot gui
bindsym Mod4+F4 exec --no-startup-id wlogout
bindsym XF86AudioRaiseVolume exec  --no-startup-id volumectl -d -u +1%
bindsym XF86AudioLowerVolume exec  --no-startup-id volumectl -d -u -1%
# bindsym $mod+period exec  rofimoji
bindsym $mod+a exec --no-startup-id swaync-client -t -sw 
bindsym $mod+c exec --no-startup-id copyq show
bindsym $mod+shift+minus move scratchpad
bindsym $mod+minus scratchpad show

bindsym XF86AudioMute exec volumectl -d %
bindsym XF86AudioMicMute exec volumectl -d -m %
bindsym XF86AudioPlay exec playerctl play-pause
bindsym XF86AudioNext exec playerctl next
bindsym XF86AudioPrev exec playerctl previous
# bindsym XF86Search exec bemenu-run
